name: Test

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash   # otherwise "set -o pipefail" is not set by GHA

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          env
          set
